### ISSUE TITLE
Use Duckduckgo for a search engine

### ISSUE THREAD

**Issue by hThoreau** [gleitz/howdoi#203]
Hello there.

My OS, much like Tails, by default routes traffic through Tor for added security. I noticed that you use google as the default search engine, and it blocks access through Tor.

Could you please pass instruction for modifying the script to add duckduckgo as an option for search engine or update to have it as an option?

Thanks.

**Comment by WindSoilder** [comment]
A little note for the custom search engine.  After add *duckduckgo* as an option for search engine, you need to config environment variable `HOWDOI_SEARCH_ENGINE` to *duckduckgo* to make howdoi use the search engine :)

**Comment by hThoreau** [comment]
I attempted to emulate the structure of the lines @gleitz pointed at for duckduckgo, and also assigned the `duckduckgo` value to `HOWDOI_SEARCH_ENGINE`. but still I'm getting a "Sorry, couldn't find any help with that topic".

I'm not familiar with Python, maybe you guys could point out my errors? I've pasted the modified script [here](https://gist.github.com/hThoreau/6264d823ed92ec426cb36e97c5771f37). The lines that I've modified are 65, 110 to 112, 119 to 122, 129 to 131. You'll notice I used duckduckgo's onion address. I believe that this shouldn't be a problem, as all my connections are routed through tor by default. For example, elinks and curl are able to access it just as any other address.

**Comment by WindSoilder** [comment]
Hi, I think the mainly problem lays in your code is `_extract_links_from_duckduckgo(html)` which in line `110`, because different search engine have different page layout, you shouldn't parse the same way like `bing` search engine.  
may be you can re-implement your `_extract_links_from_duckduckgo` function like this:

```python
def _extract_links_from_duckduckgo(html):
    return [a.attrib['href'] for a in html('#links')('h2')('.result__a')]
```

Due to my network problem.. I can access `duckduckgo` in my browser, but I can't access it through `howdoi`.  So I haven't test my code :(  But I hope this can help you solve the problem :)

**Comment by hThoreau** [comment]
Thanks for the suggestion @WindSoilder, I still got the same result though. :slightly_frowning_face:

**Comment by gleitz** [comment]
Closing this for now. Please re-open when you have a working PR.
