### ISSUE TITLE
Stash command

### ISSUE THREAD

**Issue by chrisngyn** [gleitz/howdoi#286]
I mentioned this in our last meeting; I would like to make a feature that can stash answers in its own cache that you can access. For example:

`$ howdoi while loop python`
`$ {response from howdoi}`
`$ howdoi -s while loop python` (where **-s** is stash)
`$ howdoi -vs` (where **-vs** is view stash)
`$ [{ans1}, {ans2}, {ans3} ...]` (where all the answers are the JSON objects respectively for the answers we stored)

Let me know how you would like to see this implemented. @YKo20010 and I will be working on it.

**Comment by gleitz** [comment]
I did a little digging and found some projects that allows you to keep commands and snippets for later: 

https://github.com/orkohunter/keep
https://github.com/knqyf263/pet

Before we build this as part of howdoi, is it possible to integrate with any of these existing services? We should also understand what these services offer (syncing to github/gist, search, etc).

Integration to an existing project might be more useful rather than trying to maintain something like this ourselves, and we can also leverage the improvements those projects get from the community.

**Comment by chrisngyn** [comment]
These two projects are really interesting; I'll see how we can integrate them with howdoi!

**Comment by gmelodie** [comment]
This sounds a lot like a cache. Maybe we could use the cache as the stash? I'm not sure if it keeps the order of answers though.
