### ISSUE TITLE
Any thought for paging feature?

### ISSUE THREAD

**Issue by WindSoilder** [gleitz/howdoi#314]
Hi, thanks for your project.  I have tried to implement it in another language.

And finally I have added a paging feature(according to others suggestions), when we get answer too long, it will output the information to `less` command, so user can view output one by one page.

You can see the result here: https://github.com/WindSoilder/hors#screenshot

I think it's a fantasty feature, so I share the idea here.  Maybe it's useful and we can have this in howdoi.  What do you think? :-)

**Comment by gmelodie** [comment]
I think that's a rather interesting feature (shouldn't be super hard to implement as well). @gleitz what do you think?

**Comment by gracewgao** [comment]
@Ochibobo and I would love to give this a try!

**Comment by gleitz** [comment]
Very cool @WindSoilder! Love the rust implementation. 

Question on the paging feature - what's the difference between:

`hors mysql create table with column comment -a -n 10`
and
`howdoi mysql create table with column comment -a -n 10 | less`

I think it's preferable that you have to pipe to `less` (or `more`) because then it's easy to pipe to other utilities without issue. For example 

`hors mysql create table with column comment -a -n 10 | less` 
has errors with strange escape sequences that appear like 
`ESC[0mESC[38;2;211;208;200mQuery OK, 0 rows affected (0.41 sec)`

The same issue happens for 
`hors mysql create table with column comment -a -n 10 | pbcopy` 
if you want to get the result on your clipboard.

If you only use howdoi/hors in the terminal I can see where it makes sense to automatically pipe to less, but for interoperability I feel this function should at least be off by default so it will play nice with other pipes. And if you're always turning it on, then you might as well add the `| less` or make an alias

```
howdoi_less() {
  howdoi $@ | less
}
```

**Comment by WindSoilder** [comment]
Hi, @gleitz 
> what's the difference between:
hors mysql create table with column comment -a -n 10
and
howdoi mysql create table with column comment -a -n 10 | less

It's nothing so special, `hors` is just running `less` command inside.  But to make less colorize output, it should contains `"--raw-control-chars", "--quit-if-one-screen", "--no-init"` parameter.

> If you only use howdoi/hors in the terminal I can see where it makes sense to automatically pipe to less, but for interoperability I feel this function should at least be off by default so it will play nice with other pipes. And if you're always turning it on, then you might as well add the | less or make an alias

Hmm... Agree with your idea :-)  For now hors is automatically pipe to less is on by `default`, but have additional parameter `--paging` to control the behavior.  Maybe I need to think about the position of howdoi/hors.

Use shell pipes seems more ergonomic, I think we can point this feature out to doc, just to tell user that `howdoi` can be paging like:

    howdoi mysql create table with column comment -a -n 10 | less "--raw-control-chars", "--quit-if-one-screen", "--no-init"

what do you think?

**Comment by gleitz** [comment]
Thanks! Added as an alias

https://github.com/gleitz/howdoi/commit/86805a177488bc96b8dbb643e9cf69db93800104
