### ISSUE TITLE
os.environ['HOWDOI_SEARCH_ENGINE'] might not be respected

### ISSUE THREAD

**Issue by gleitz** [gleitz/howdoi#377]
After https://github.com/gleitz/howdoi/pull/370/files we may not be respecting the env variable for the search engine. Need to have a check like we used to

```
    if args['search_engine'] != 'google':
        os.environ['HOWDOI_SEARCH_ENGINE'] = args['search_engine']
```

**Comment by gleitz** [comment]
This query should return "bing"

```
HOWDOI_SEARCH_ENGINE=bing python -m howdoi format date bash --explain
```

question: what should happen with

```
HOWDOI_SEARCH_ENGINE=bing python -m howdoi format date bash --explain --engine duckduckgo
```

**Comment by gmelodie** [comment]
Here's my idea of approach to it (discussed with @ShezaMunir earlier):
1. Use `--engine` if specified on the command line
2. Otherwise use `HOWDOI_SEARCH_ENGINE` environment variable if set
3. Otherwise use default (`google` as of now)

> question: what should happen with
```
HOWDOI_SEARCH_ENGINE=bing python -m howdoi format date bash --explain --engine duckduckgo
```

Answer: as of now, none are respected and google is used. Using my approach `--engine` should be respected over the environment variable

**Comment by gleitz** [comment]
Sounds good to me!

**Comment by ShezaMunir** [comment]
Just opened a PR. It is respecting the env variable for the search engine now. However, for setting the preference that which one (env variable or `--engine`) should be used, I worked with two approaches:
 
1.   `--engine` will be preferred over the env variable
2. In case google is one of the conflicting choices, the non-google search engine will be preferred, wherever it is specified, in the env variable or with `--engine`
 
Thanks for the help @gmelodie!
