### ISSUE TITLE
Howdoi history

### ISSUE THREAD

**Issue by joeyouss** [gleitz/howdoi#405]
If we could create a local database or something like a flag ```howdoi --history``` to see what our search history has been.

**Comment by ShezaMunir** [comment]
Like we discussed in our meeting today, looking into the conflicts on this [PR](https://github.com/gleitz/howdoi/pull/303) would be helpful

**Comment by gleitz** [comment]
I have a few thoughts on this idea:

- Collecting data, especially around your search queries, needs consideration because many users might not want to be tracked. It's probably less sensitive than your browser history, but still requires thought.
- Your command line will remember your previous search queries (in bash you can use `ctrl+r`) so pressing that key and typing `howdoi python` will show you all the queries you made that include those words. I'm reluctant to add this functionality to howdoi when it already exists via the command line.
- We do have the `stash` functionality if you really want to save a particularly useful answer.

**Comment by joeyouss** [comment]
Yes, makes sense
